---
- include: rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'

- include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install dotnet core
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ dotnet_packages }}"
  
- fail:
    msg: The variable `dotnet_package` is deprecated. Use `dotnet_packages` instead
  when: dotnet_package is defined
  ignore_errors: yes